/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    Card: typeof import('./src/components/Card.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    CartItemList: typeof import('./src/components/CartItemList.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    DrawerHead: typeof import('./src/components/DrawerHead.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoBlock: typeof import('./src/components/InfoBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
